### ISSUE TITLE
How to access the files in the route ?

### ISSUE THREAD

**Issue by daslicht** [stuartha13/meteor-busboy#1]
Hello,
the busboy middleware seams to work but how do I access the files in my route ?

I tried this, but req.files is always undefined?:

```
Router.route('/imageUpload', {where: 'server'}).post(function (req, res, next) {

    console.log(req.file);

  });

```

**Comment by stuartha13** [comment]
Hi @daslicht 

Sorry, I haven't looked at this code in ages!

Is that the complete snippet for your route? Have you already got the onBeforeAction set up?

From what I remember, you can only get your file information from within the `"file"` event, which is handled in the `onBeforeAction` in the example I put in the readme.

If you look further down in the example, in the `"finish"` event, you can see that I added the file to the request, and then we pass the request back to busboy.

So, if that is all running, you should be able to see the files in the request using:

``` js
Router.route('/imageUpload', {where: 'server'}).post(function () {
    var req = this.request;
    console.log(req.file);
});
```

If this doesn't help you, I can send you a more complete example that I've implemented in a project of mine.

**Comment by daslicht** [comment]
Hello,
I have managed to get the uploaded file no in my route and struggeling how to save that file into gridfs :)

**Comment by stuartha13** [comment]
Haha! Good luck! :)
